name: Versioning

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Changesets Versioning
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    environment: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: 18.x

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Create Version Packages Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn exec .changeset/version.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
